
# - the latest version of R for the Ubuntu Xenial release
# - Several associated R packages
# - Rstudio Desktop 1.0.143-amd64
# - Rstudio Server 1.0.143-amd64
# - Some R packages and BioConductor/BioConductor packages

---
    - name: Check if desired CRAN source exist
      remote_user: root
      shell: grep "deb https://cran.cnr.berkeley.edu/bin/linux/ubuntu xenial/" /etc/apt/sources.list
      register: CRAN_check
      ignore_errors: true

    - name: Update CRAN source if necessary
      remote_user: root
      shell: echo "deb https://cran.cnr.berkeley.edu/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list
      when: CRAN_check|failed

    - name: Update sources
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install R base and r-base-dev and associated packages
      apt:
       name="{{ item }}" state=installed
       install_recommends=yes
       allow_unauthenticated=yes
      with_items:
       - r-base
       - r-base-dev
       - gdebi-core
       - libxml2-dev
       - libssl-dev
       - libcurl4-openssl-dev

    - name: Check if rstudio desktop is installed
      shell: dpkg -l|grep "rstudio\s"
      register: rstudio_desktop_check
      ignore_errors: true

    - name: Download rstudio desktop
      get_url:
        url: https://download1.rstudio.org/rstudio-1.0.143-amd64.deb
        dest: /home/{{ansible_user}}/rstudio-1.0.143-amd64.deb
      when: rstudio_desktop_check|failed

    - name: Install rstudio desktop
      command: gdebi -n /home/{{ansible_user}}/rstudio-1.0.143-amd64.deb
      when: rstudio_desktop_check|failed
      become: true

    - name: Check if rstudio-server is installed
      shell: dpkg -l |grep "rstudio-server"
      register: rstudio_server_check
      ignore_errors: true

    - name: Download rstudio server
      get_url:
        url: https://download2.rstudio.org/rstudio-server-1.0.143-amd64.deb
        dest: /home/{{ansible_user}}/rstudio-server-1.0.143-amd64.deb
      when: rstudio_server_check|failed

    - name: Install rstudio server
      command: gdebi -n /home/{{ansible_user}}/rstudio-server-1.0.143-amd64.deb
      when: rstudio_server_check|failed
      become: true

    - name: Install general R packages (tidyverse)
      command: >
          Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('https://cran.cnr.berkeley.edu/')); print('Added'); } else { print('Already installed'); }"
      register: r_result
      failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
      changed_when: "'Added' in r_result.stdout"
      with_items:
        - tidyverse
...
